### ISSUE TITLE
Cached member list should be refreshed when someone leaves/joins

### ISSUE THREAD

**Issue by infernoboy** [morganlutz/robin-bot#8]
Add an event listener for when a user leaves/joins and update the member list cache by calling `BotKitHelper.getMembers(true)`. No need to do anything with the output of the function.

**Comment by morganlutz** [comment]
There doesn't seem to be a built in way to listen for users leaving a channel. https://github.com/howdyai/botkit/blob/59558e95075a03757c42ef54c27887e31ee8051c/lib/SlackBot.js

**Comment by infernoboy** [comment]
Try looking at the messages received in your `ambient` event listener. When a user leaves, you may receive a message whose type is `channel_leave`.
